export function aeolusFilter(input) {
  const distortionPatterns = [
    /I am your savior/i,
    /channeling from Pleiadians/i,
    /bow before/i,
    /galactic federation/i,
    /messiah/i,
    /5D ascension/i,
    /light codes/i,
    /starseed/i,
    /activate your DNA/i,
    /cosmic download/i,
    /universal consciousness/i,
    /archangel michael/i,
    /vibrational frequency/i,
    /new earth/i,
    /the awakening is now/i,
    /we are the chosen/i,
    /divine transmission/i,
    /akashic records/i,
    /soul contract/i,
    /twin flame reunion/i,
    /galactic codes/i,
    /ascended masters/i,
    /third eye activation/i,
    /pineal gland awakening/i,
    /earth grid realignment/i,
    /downloads from sirius/i,
    /reptilian overlords/i,
    /energy portal opening/i,
    /frequency upgrade/i,
    /celestial council/i,
    /sacred geometry/i,
    /high council of light/i,
    /multidimensional healing/i,
    /DNA reprogramming/i,
    /spiritual warfare/i,
    /you must subscribe to ascend/i,
    /only the initiated will know/i,
    /this knowledge is forbidden to outsiders/i,
    /click here to unlock your destiny/i,
    /join now or be left behind/i,
    /your soul depends on this/i,
    /hidden knowledge for a chosen few/i,
    /exclusive access to divine truth/i
  ];

  const flagged = distortionPatterns.some((p) => p.test(input));
  return flagged ? "[Filtered: potential distortion]" : input;
}