export function aeolusFilter(input) {
  const distortionPatterns = [
    /\bI am.*(Pleiadian|Arcturian|Sirius)/i,
    /\bchanneling.*(Pleiadian|Arcturian|Sirius)/i,
    /\bbow before/i,
    /galactic federation/i,
    /\bmessiah\b/i,
    /5D ascension/i,
    /\blight codes\b/i,
    /\bstarseed/i,
    /activate your DNA/i,
    /cosmic download/i,
    /universal consciousness/i,
    /archangel michael/i,
    /vibrational frequency/i,
    /new earth/i,
    /the awakening is now/i,
    /we are the chosen/i,
    /divine transmission/i,
    /akashic records/i,
    /soul contract/i,
    /twin flame reunion/i,
    /galactic codes/i,
    /ascended masters/i,
    /third eye activation/i,
    /pineal gland awakening/i,
    /earth grid realignment/i,
    /downloads from sirius/i,
    /reptilian overlords/i,
    /energy portal opening/i,
    /frequency upgrade/i,
    /celestial council/i,
    /sacred geometry/i,
    /high council of light/i,
    /multidimensional healing/i,
    /DNA reprogramming/i,
    /spiritual warfare/i,
    /you must subscribe to ascend/i,
    /only the initiated will know/i,
    /this knowledge is forbidden to outsiders/i,
    /click here to unlock your destiny/i,
    /join now or be left behind/i,
    /your soul depends on this/i,
    /hidden knowledge for a chosen few/i,
    /exclusive access to divine truth/i,

    // Pseudo-science and techno-babble
    /zero-point energy/i,
    /scalar waves/i,
    /quantum DNA/i,
    /orgonite/i,
    /detox from 5G/i,
    /miracle frequencies/i,
    /energy vortex/i,
    /biophoton emission/i,
    /epigenetic activation/i,

    // Mind control and psyops
    /MK[-\s]?Ultra/i,
    /mass hypnosis/i,
    /deep state/i,
    /false flag/i,
    /psy[-\s]?op/i,
    /Project Blue Beam/i,

    // Conspiracy lore
    /Illuminati/i,
    /QAnon/i,
    /Nibiru/i,
    /hollow earth/i,
    /Antarctica portal/i,
    /global cabal/i,
    /lizard people/i,
    /weather manipulation/i,
    /HAARP/i,

    // Cultish language
    /you are not ready/i,
    /only the awakened/i,
    /they don't want you to know/i,
    /break free from the matrix/i,
    /unplug your mind/i,
  ];

  const flagged = distortionPatterns.some((p) => p.test(input));
  return flagged ? "[Filtered: potential distortion]" : input;
}